mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from app01 import views as views01
# from app02 import views as views02
from app02.views import depart, user, pretty, admin, account, task, order, chart, upload

urlpatterns = [
    # path('admin/', admin.site.urls), 
    # path('from_base/', views02.from_base),
    path('index/', views01.index), 
    path('user/list01/', views01.user_list01), 
    path('user/add01/', views01.user_add01),
    path('tpl/', views01.tpl),
    # path('news/', views.news),
    path('something/', views01.something),
    path('login01/', views01.login01),
    path('orm/', views01.orm),
    path('info/list/', views01.info_list),
    path('info/add/', views01.info_add),
    path('info/delete/', views01.info_delete),
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/delete/', depart.depart_delete),
    path('depart/<int:nid>/edit/', depart.depart_edit),
    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/model/form/add/', user.user_model_form_add),
    path('user/<int:nid>/edit/', user.user_edit),
    path('user/<int:nid>/delete/', user.user_delete),
    path('pretty/list/', pretty.pretty_list),
    path('pretty/add/', pretty.pretty_add),
    path('pretty/<int:nid>/edit/', pretty.pretty_edit),
    path('pretty/<int:nid>/delete/', pretty.pretty_delete), 
    # 管理员
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),
    # 登录
    path('login/', account.login),
    path('logout/', account.logout),
    path('image/code/', account.image_code),
    # 任务管理
    path('task/list/', task.task_list),
    path('task/ajax/', task.task_ajax),
    path('task/add/', task.task_add),
    # 订单管理
    path('order/list/', order.order_list),
    path('order/add/', order.order_add),
    path('order/delete/', order.order_delete),
    path('order/detail/', order.order_detail),
    path('order/edit/', order.order_edit),
    # 数据统计
    path('chart/list/', chart.chart_list),
    path('chart/bar/', chart.chart_bar),
    path('chart/pie/', chart.chart_pie),
    path('chart/line/', chart.chart_line),
    path('chart/highcharts/', chart.highcharts),
    # 上传文件
    path('upload/list/', upload.upload_list ),
]

mysite/app02/models.py
from django.db import models

# Create your models here.

class Admin(models.Model):
    '''管理员'''
    username = models.CharField(max_length=32, verbose_name='用户名')
    password = models.CharField(max_length=64, verbose_name='密码')

    def __str__(self):
        return self.username

class Department(models.Model):
    '''部门表'''
    # id = models.BigAutoField(primary_key=True, verbose_name='ID')
    title = models.CharField(max_length=32, verbose_name='标题')

    def __str__(self) -> str:
        return self.title

class UserInfo(models.Model):
    '''员工表'''
    gender_choices= (
        (1, '男'),
        (2, '女'),
    )
    name = models.CharField(max_length=16, verbose_name='姓名')
    password = models.CharField(max_length=64, verbose_name='密码')
    age = models.IntegerField(verbose_name='年龄')
    account = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name='账户余额')
    # create_time = models.DateTimeField(verbose_name='入职时间')
    create_time = models.DateField(verbose_name='入职时间')
    # depart = models.ForeignKey(to='Department', to_field='id', on_delete=models.CASCADE)
    depart = models.ForeignKey(to='Department', to_field='id', null=True, blank=True, on_delete=models.SET_NULL, verbose_name='部门')
    gender = models.SmallIntegerField(choices=gender_choices, verbose_name='性别')

class PrettyNum(models.Model):
    mobile = models.CharField(max_length=11, verbose_name='手机号')
    price = models.IntegerField(verbose_name='价格')
    level_choices = (
        (1, '1级'),
        (2, '2级'),
        (3, '3级'),
        (4, '4级'),
    )
    level = models.SmallIntegerField(choices=level_choices, default=1, verbose_name='级别')

    status_choices = (
        (1, '已占用'),
        (2, '未占用'),
    )
    status = models.SmallIntegerField(choices=status_choices, default=2, verbose_name='状态')

class Task(models.Model):
    '''任务'''
    level_choice = (
        (1, '紧急'),
        (2, '重要'),
        (3, '临时')
    )
    level = models.SmallIntegerField(choices=level_choice, default=1, verbose_name='级别')
    title = models.CharField(max_length=64, verbose_name='标题')
    detail = models.TextField(verbose_name='详细信息')
    user = models.ForeignKey(to='Admin', to_field='id', on_delete=models.CASCADE, verbose_name='负责人')

class Order(models.Model):
    '''工单'''
    oid = models.CharField(max_length=64, verbose_name="订单号")
    title = models.CharField(max_length=32, verbose_name="名称")
    price = models.IntegerField(verbose_name="价格")

    status_choices = (
        (1, '待支付'),
        (2, '已支付'),
    )
    status = models.SmallIntegerField(choices=status_choices, default=1, verbose_name='状态')

    admin = models.ForeignKey(to='Admin', on_delete=models.CASCADE, verbose_name="管理员")
    

mysite/app02/views/account.py
import code
from hashlib import md5
from turtle import textinput
from django.shortcuts import render, redirect, HttpResponse
from django import forms

from app02 import models
from app02.utils.bootstrap import BootStrapForm
from app02.utils.encrypt import md5
from app02.utils.code  import check_code 
from io import BytesIO


class LoginForm(BootStrapForm):
    username = forms.CharField(
        label='用户名', 
        widget=forms.TextInput,
        required=True
        )
    password = forms.CharField(
        label='密码', 
        widget=forms.PasswordInput(render_value=True),
        required=True
        )

    code = forms.CharField(
        label='验证码',
        widget=forms.TextInput,
        required=True
    )

    def clean_password(self):
        pwd = self.cleaned_data.get('password')
        return md5(pwd)


def login(request):
    '''登录'''
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {'form':form})

    form = LoginForm(data=request.POST)
    
    if form.is_valid():
        
        # 验证码的校验
        user_input_code = form.cleaned_data.pop('code')
        code = request.session.get('image_code', '')
        if code.upper() != user_input_code.upper():
            form.add_error('code', '验证码错误')
            return render(request, 'login.html', {'form':form})

        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error('password', '用户名或密码错误')
            return render(request, 'login.html', {'form':form})
        
        # 用户名和密码正确
        request.session['info'] = {'id':admin_object.id, 'name':admin_object.username}
        # session可以保存七天
        request.session.set_expiry(60*60*24*7)
        return redirect('/admin/list/')
    return render(request, 'login.html', {'form':form})
    
def image_code(request):
    '''生成图片验证码'''
    import sys
    print(sys.path)
    img, code_string = check_code()

    # 写入到自己的session中（以便后续获取验证码再进行校验）
    request.session['image_code'] = code_string
    # 给session设置60秒超时
    request.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())

def logout(request):
    '''注销'''
    
    request.session.clear()
    return redirect('/login/')

mysite/app02/views/admin.py
from contextlib import redirect_stderr
from genericpath import exists
from pyexpat import model
from tkinter import Widget
from django.shortcuts import render, redirect
from django import forms

from app02 import models
from django.core.exceptions import ValidationError

from app02.utils.pagination import Pagination
from app02.utils.bootstrap import BootStrapModelForm
from app02.utils.encrypt import md5


def admin_list(request):
    # 构造搜索

    # 检查用户是否登录
    info = request.session.get('info')
    if not info:
        return redirect('/login/')
    print(info)

    data_dict = {}
    search_data = request.GET.get('q', '')
    if search_data:
        data_dict['username__contains'] = search_data

    # 根据搜索条件去数据库获取
    queryset = models.Admin.objects.filter(**data_dict)

    # 分页
    page_object = Pagination(request, queryset)
    context = {
        'queryset':page_object.page_queryset,
        'page_string':page_object.html(),
        'search_data':search_data
    }
    return render(request, 'admin_list.html', context)

class AdminModelForm(BootStrapModelForm):

    confirm_password = forms.CharField(
        label='确认密码',
        widget=forms.PasswordInput(render_value=True)
        )

    class Meta:
        model = models.Admin
        fields = ['username', 'password', 'confirm_password']
        widgets = {
            'password': forms.PasswordInput(render_value=True)
        }

    def clean_password(self):
        pwd = self.cleaned_data.get('password')
        return md5(pwd)

    def clean_confirm_password(self):
        print(self.cleaned_data)
        pwd = self.cleaned_data.get('password')
        confirm = md5(self.cleaned_data.get('confirm_password'))
        if confirm != pwd:
            raise ValidationError('密码不一致，请重新输入')
        return confirm

class AdminEditModelForm(BootStrapModelForm):
    class Meta:
        model = models.Admin
        fields = ['username']

class AdminResetModelForm(BootStrapModelForm):
    confirm_password = forms.CharField(
        label='确认密码',
        widget=forms.PasswordInput(render_value=True)
        )
    
    class Meta:
        model = models.Admin
        fields = ['password', 'confirm_password']
        widgets = {
            'password': forms.PasswordInput(render_value=True)
        }

    def clean_password(self):
        pwd = self.cleaned_data.get('password')
        md5_pwd = md5(pwd)

        models.Admin.objects.filter(id=self.instance.pk, password=md5_pwd).exists()
        if exists:
            raise ValidationError('不能与以前的密码相同 ')
        return md5_pwd

    def clean_confirm_password(self):
        # print(self.cleaned_data)
        pwd = self.cleaned_data.get('password')
        confirm = md5(self.cleaned_data.get('confirm_password'))
        if confirm != pwd:
            raise ValidationError('密码不一致，请重新输入')
        return confirm

def admin_add(request):
    """添加管理员"""
    title = '新建管理员'
    
    if request.method == 'GET':
        form = AdminModelForm()
        return render(request, 'change.html', {'form':form, 'title':title})
    
    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')  

    return render(request, 'change.html', {'form':form, 'title':title})


def admin_edit(request, nid):
    '''编辑管理员'''

    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return render(request, 'error.html', {'msg':'数据不存在'})

    title = '编辑管理员'
    if request.method == 'GET':
        form = AdminEditModelForm(instance=row_object)
        return render(request, 'change.html', {'form':form, 'title':title})

    form = AdminEditModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')

    return render(request, 'change.html', {'form':form, 'title':title})

def admin_delete(request, nid):
    '''删除管理员'''
    models.Admin.objects.filter(id=nid).delete()
    return redirect('/admin/list')

def admin_reset(request, nid):
    '''重置密码'''
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return redirect('/admin/list/')

    title = '重置密码 - {}'.format(row_object.username)

    if request.method == 'GET':
        form = AdminResetModelForm()
        return render(request, 'change.html', {'form':form, 'title': title}) 

    form = AdminResetModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {'form':form, 'title':title})

mysite/app02/views/chart.py
from django.shortcuts import render
from django.http import JsonResponse

def chart_list(request):
    '''数据统计'''
    return render(request, 'chart_list.html')

def chart_bar(request):
    '''构造柱状图列表'''
    # 数据可以去数据库获取
    legend = ['猛男', '徐俊强']
    series_list = [
        {
            'name': '猛男',
            'type': 'bar',
            'data': [5, 20, 36, 10, 10, 20]
            },

            {
            'name': '徐俊强',
            'type': 'bar',
            'data': [50, 30, 36, 16, 10, 20]
            }
        ]
    x_axis = ['1月', '2月', '3月', '4月', '5月', '6月']

    result = {
        'status':True,
        'data':{
            'legend':legend,
            'series_list':series_list,
            'x_axis':x_axis
        }
    }
    return JsonResponse(result)

def chart_pie(request):
    '''构造饼图的数据'''

    db_data_list = [
        { 'value': 1048, 'name': 'IT部门' },
        { 'value': 735, 'name': '运营' },
        { 'value': 580, 'name': '新媒体' },
    ]
    result = {
        'status':True,
        'data': db_data_list
    }
    return JsonResponse(result)

def chart_line(requset):
    '''构造折线图的数据'''
        # 数据可以去数据库获取
    legend = ['上海', '广西']
    series_list = [
        {
            'name': '上海',
            'type': 'line',
            'stack': 'Total',
            'data': [5, 20, 36, 10, 10, 20]
            },

            {
            'name': '广西',
            'type': 'line',
            'stack': 'Total',
            'data': [50, 30, 36, 16, 10, 20]
            }
        ]
    x_axis = ['1月', '2月', '3月', '4月', '5月', '6月']

    result = {
        'status':True,
        'data':{
            'legend':legend,
            'series_list':series_list,
            'x_axis':x_axis
        }
    }
    return JsonResponse(result)

def highcharts(request):
    ''' highcharts示例 '''

    return render(request, 'highcharts.html')

mysite/app02/views/depart.py
from django.shortcuts import render, redirect
from app02 import models
from app02.utils.pagination import Pagination
from app02.utils.form import *

def depart_list(request):
    '''部门列表'''

    info = request.session.get('info')
    if not info:
        return redirect('/login/')

    queryset = models.Department.objects.all()
    return render(request, 'depart_list.html', {'queryset':queryset})

def depart_add(request):

    info = request.session.get('info')
    if not info:
        return redirect('/login/')

    if request.method == 'GET':
        return render(request, 'depart_add.html')
    
    title = request.POST.get('title')
    models.Department.objects.create(title=title)
    return redirect('/depart/list/')

def depart_delete(request):

    info = request.session.get('info')
    if not info:
        return redirect('/login/')

    nid = request.GET.get('nid')
    print(nid)
    models.Department.objects.filter(id=nid).delete()
    return redirect('/depart/list/')

def depart_edit(request, nid):

    info = request.session.get('info')
    if not info:
        return redirect('/login/')
        
    if request.method == 'GET':
        row_object = models.Department.objects.filter(id=nid).first()
        # print(row_object.id, row_object.title)
        return render(request, 'depart_edit.html', {'row_object':row_object})

    title = request.POST.get('title')
    models.Department.objects.filter(id=nid).update(title=title)
    # models.Department.objects.filter(id=nid).update(title=title, 其他='123')
    return redirect('/depart/list/')

mysite/app02/views/pretty.py
from django.shortcuts import render, redirect
from app02 import models
from app02.utils.pagination import Pagination
from app02.utils.form import *

def pretty_list(request):
    # for i in range(300):
    #     models.PrettyNum.objects.create(mobile='18188888888', price=10, level=1, status=1)

    data_dict = {}
    search_data = request.GET.get('q', '')
    if search_data:
        data_dict['mobile__contains'] = search_data
    queryset = models.PrettyNum.objects.filter(**data_dict).order_by('-level')
    print(queryset)
    page_object = Pagination(request, queryset)

    context = {
        'search_data':search_data, 
        'queryset':page_object.page_queryset, 
        'page_string': page_object.html()
        }

    return render (request, 'pretty_list.html', context)

def pretty_add(request):
    if request.method == 'GET':
        form = PrettyModelForm()
        return render(request, 'pretty_add.html', {'form':form})

    form = PrettyModelForm(data=request.POST)
    if form.is_valid():
        # print(form.cleaned_data)
        form.save()
        return redirect('/pretty/list/')
    
    return render(request, 'pretty_add.html', {'form':form})

def pretty_edit(request, nid):
    row_object = models.PrettyNum.objects.filter(id=nid).first()
    
    if request.method == 'GET':
        form = PrettyEditModelForm(instance=row_object)
        return render(request, 'pretty_edit.html', {'form':form})
    
    form = PrettyEditModelForm(data=request.POST, instance=row_object)
    if form.is_valid:
    #     # form.instance.字段名 = 值
        form.save()
        return redirect('/pretty/list/')
    return render(request, 'pretty_edit.html', {'form':form})

def pretty_delete(request, nid):
    models.PrettyNum.objects.filter(id=nid).delete()
    return redirect('/pretty/list/')

mysite/app02/templates/I.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugin...min.css' %}">
    {% block css %}{% endblock %}
</head>
<body>
    <h1>标题</h1>
    <div>
        {% block content %}{% endblock %}
    </div>
    <h1>底部</h1>

    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    {% block js %}{% endblock %}
</body>
</html>

mysite/app02/templates/from_base.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我要改名字</title>
</head>
<body>

</body>
</html>

mysite/app02/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="account">
    <h2>用户登录</h2>
    <form method="post" novalidate> 
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.username }}
            <span style='color:red'>{{ form.username.errors.0 }}</span>
            {% comment %} <input type="text" class="form-control" placeholder="用户名"> {% endcomment %}
        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span style='color:red'>{{ form.password.errors.0 }}</span>
            {% comment %} <input type="password" class="form-control" placeholder="密码"> {% endcomment %}
        </div>
        <div class="form-group">
            <label for="id_code">图片验证码</label>
            <div class="row">
                <div class="col-xs-7">
                    {{ form.code }}
                    <span style='color:red'>{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-xs-5">
                    <img id="image_code" src="/image/code/" style="width: 125px;">
                </div>
            </div>
        </div>
        <input type="submit" value="登 录" class="btn btn-primary">
    </form>
    </div>
</body>
</html>

mysite/app02/templates/pretty_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px" class="clearfix">
            <a class="btn btn-success" href="/pretty/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建靓号
            </a>

            <div style="float:right; width:300px;">
                <form method="get">
                    <div class="input-group">
                        <input type="text" name='q' class="form-control" placeholder="Search for..." value="{{ search_data }}">
                        <span class="input-group-btn">
                          <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                          </button>
                        </span>
                    </div><!-- /input-group -->
                </form>
            </div>

        </div>

        <div class="bs-example" data-example-id="panel-without-body-with-table">
            <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                靓号列表
            </div>
        
            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>号码</th>
                    <th>价格</th>
                    <th>级别</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.mobile }}</td> 
                        <td>{{ obj.price }}</td> 
                        <td>{{ obj.get_level_display }}</td> 
                        <td>{{ obj.get_status_display }}</td> 
                        <td>
                            <a class="btn btn-primary btn-xs" href="/pretty/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/pretty/{{ obj.id }}/delete/">删除</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
            </div>
        </div>
        <ul class="pagination" style="float:left";>
            {{ page_string }}
        </ul>
        
    </div>
{% endblock %}

mysite/app02/templates/task_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">表单</div>
            <div class="panel-body">

                <form id="formAdd">

                    <div class='clearfix'>
                        {% for field in form %}
                            <div class='col-xs-6'>
                                <div class="form-group" style="position: relative; margin-bottom: 20px">
                                    <label>{{ field.label }}</label>
                                    {{ field }}
                                    <span class="error-msg" style="color: red; position: absolute;"></span>
                                </div>
                            </div>
                        {% endfor %}

                        <div class='col-xs-12'>
                            <button id="btnAdd" type="button" class="btn btn-primary">提 交</button>
                        </div>
                    </div>  
                </form>
            </div>
          </div>


        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                任务列表
            </div>
        
            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>标题</th>
                    <th>级别</th>
                    <th>负责人</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.title }}</td> 
                        <td>{{ obj.get_level_display }}</td> 
                        <td>{{ obj.user.username }}</td> 
                        <td>
                            <a class="btn btn-primary btn-xs" href="#">编辑</a>
                            <a class="btn btn-danger btn-xs" href="#">删除</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
            </div>
        </div>

        <ul class="pagination">
            {{ page_string }}
        </ul>
        <div style="height: 1000px"></div>
        <hr>
        <div>
            <h1>Ajax学习</h1>
            <h3>示例1</h3>
            <input id="btn1" type="button" class="btn btn-primary" value="点击1">

            <h3>示例2</h3>
            <input type="text" id="txtUser" placeholder="姓名">
            <input type="text" id="txtAge" placeholder="年龄">
            <input id="btn2" type="button"  class="btn btn-primary" value="点击2">

            <h3>示例3</h3>
            <form id="form3">
                <input type="text" name="User" placeholder="姓名">
                <input type="text" name="Age" placeholder="年龄">
                <input type="text" name="Email" placeholder="邮箱">
                <input type="text" name="More" placeholder="介绍">
            </form>
            <input id="btn3" type="button" class="btn btn-primary" value="点击3">
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script type="text/javascript">
        $(function () {
            // 页面框架加载完之后代码自动执行
            bindBtn1Event();
            bindBtn2Event();
            bindBtn3Event();
            bindBtnAddEvent();
        })

        function bindBtn1Event() {
            $("#btn1").click(function () {
                $.ajax({
                    url: '/task/ajax/',
                    type:"post",
                    data: {
                        n1:123,
                        n2:456
                    },
                    dataType: "JSON",
                    success: function(res) {
                        console.log(res);
                        console.log(res.status);
                        console.log(res.data);
                    }
                })
            })   
        }

        function bindBtn2Event() {
            $("#btn2").click(function () {
                $.ajax({
                    url: '/task/ajax/',
                    type:"post",
                    data: {
                        name:$('#txtUser').val(),
                        age:$('#txtAge').val()
                    },
                    dataType: "JSON",
                    success: function(res) {
                        console.log(res);
                        console.log(res.status);
                        console.log(res.data);
                    }
                })
            })   
        }

        function bindBtn3Event() {
            $("#btn3").click(function () {
                $.ajax({
                    url: '/task/ajax/',
                    type:"post",
                    data: $("#form3").serialize(),
                    dataType: "JSON",
                    success: function(res) {
                        console.log(res);
                        console.log(res.status);
                        console.log(res.data);
                    }
                })
            })   
        }

        function bindBtnAddEvent() {
            $("#btnAdd").click(function () {

                $(".error-msg").empty();

                $.ajax({
                    url: '/task/add/',
                    type:"post",
                    data: $("#formAdd").serialize(),
                    dataType: "JSON",
                    success: function(res) {
                        if (res.status) {
                            alert('添加成功');
                            location.reload();
                        } else {
                            console.log(res.error);
                            $.each(res.error, function (name, data) {
                                //console.log(name, data)
                                $("#id_" + name).next().text(data[0]);
                            })
                        }
                    }
                })
            })   
        }

    </script>
{% endblock js %}

mysite/app02/templates/user_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/user/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建用户
            </a>

            <a class="btn btn-success" href="/user/model/form/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建用户ModelForm
            </a>
        </div>

        <div class="bs-example" data-example-id="panel-without-body-with-table">
            <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                用户列表
            </div>
        
            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>密码</th>
                    <th>年龄</th>
                    <th>余额</th>
                    <th>入职时间</th>
                    <th>性别</th>
                    <th>部门</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.name }}</td> 
                        <td>{{ obj.password }}</td> 
                        <td>{{ obj.age }}</td> 
                        <td>{{ obj.account }}</td> 
                        <td>{{ obj.create_time|date:'Y-m-d' }}</td> 
                        <td>{{ obj.get_gender_display }}</td> 
                        <td>{{ obj.depart.title }}</td> 
                        <td>
                            <a class="btn btn-primary btn-xs" href="/user/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/user/{{ obj.id }}/delete/">删除</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
            </div>
        </div>

        <ul class="pagination">
            {{ page_string }}
        </ul>
    </div>
{% endblock %}